---
- name: Reload NFS exports
  ansible.builtin.command:
    argv:
      - /usr/sbin/exportfs
      - -ra
  changed_when: true

- name: Regenerate the OOD Apache portal
  ansible.builtin.command:
    argv:
      - /opt/ood/ood-portal-generator/sbin/update_ood_portal
  changed_when: true
  listen: Apply OOD portal changes

- name: Restart Apache after regenerating the portal
  ansible.builtin.systemd_service:
    name: apache2.service
    state: restarted
  listen: Apply OOD portal changes

- name: Restart all user PUNs
  ansible.builtin.command:
    argv:
      - /opt/ood/nginx_stage/sbin/nginx_stage
      - nginx_clean
      - -f
  changed_when: true
  when: not ansible_check_mode

- name: Restart the OOD exporter
  ansible.builtin.systemd_service:
    name: ondemand_exporter.service
    state: restarted
    daemon_reload: true
  when: not ansible_check_mode
