---
- name: Restart MariaDB
  ansible.builtin.systemd_service:
    name: mariadb.service
    state: restarted
  when: not ansible_check_mode

- name: Restart SlurmDBD
  ansible.builtin.systemd_service:
    name: slurmdbd.service
    state: restarted
  when: not ansible_check_mode
