name: IApp runtime issue
description: Report submission, runtime, or teardown problems for an Interactive App (IApp)
title: "[IApp] <brief summary>"
labels: ["area:iapp", "type:bug", "needs-triage"]
body:
  - type: dropdown
    id: app
    attributes:
      label: Affected IApp
      options:
        - code-server
        - jupyter
        - script
        - tensorboard
        - ttyd
        - grafana
        - prometheus
        - not listed
    validations:
      required: true

  - type: dropdown
    id: cluster
    attributes:
      label: Cluster / partition
      options:
        - gpu-4070
        - cpu
    validations:
      required: true

  - type: input
    id: jobid
    attributes:
      label: Slurm Job ID (if any)
      placeholder: "e.g. 123"

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide the smallest set of steps that reproduces the problem
      placeholder: |
        1) OOD → Interactive Apps → Jupyter
        2) Select partition gpu-4070, GRES=1
        3) Submit; the session card shows ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs / outputs
      description: IApp session output, Slurm output, browser console errors, screenshots, etc.

  - type: checkboxes
    id: agree
    attributes:
      label: Pre-submission checks
      options:
        - label: I searched existing issues and found no duplicate
          required: true
