cluster_users:
  - name: liuhongbo
    uid: 10000
    gid: 10000
    home: /home/liuhongbo
    shell: /bin/bash
    groups:
      - EPIC-RL
    ssh_access:
      - epic-cluster-compute-a100-01
      - epic-cluster-compute-rtx4070-01
  - name: yinjiajie
    uid: 10001
    gid: 10001
    home: /home/yinjiajie
    shell: /bin/bash
    groups:
      - EPIC-RL
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: wangtongyu
    uid: 10002
    gid: 10002
    home: /home/wangtongyu
    shell: /bin/bash
    groups:
      - EPIC-RL
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: yinshu
    uid: 10003
    gid: 10003
    home: /home/yinshu
    shell: /bin/bash
    groups:
      - EPIC-RL
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: huodongkun
    uid: 10004
    gid: 10004
    home: /home/huodongkun
    shell: /bin/bash
    groups: []
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: jiruinan
    uid: 10005
    gid: 10005
    home: /home/jiruinan
    shell: /bin/bash
    groups:
      - EPIC-RL
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: yeyuanlin
    uid: 10006
    gid: 10006
    home: /home/yeyuanlin
    shell: /bin/bash
    groups:
      - EPIC-RL
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: wangjingnan
    uid: 10007
    gid: 10007
    home: /home/wangjingnan
    shell: /bin/bash
    groups:
      - EPIC-RL
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: zhangjiahao
    uid: 10008
    gid: 10008
    home: /home/zhangjiahao
    shell: /bin/bash
    groups:
      - EPIC-RL
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: liuyijing
    uid: 10009
    gid: 10009
    home: /home/liuyijing
    shell: /bin/bash
    groups: []
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: yanghao
    uid: 10010
    gid: 10010
    home: /home/yanghao
    shell: /bin/bash
    groups:
      - EPIC-RL
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: xiangxuxin
    uid: 10011
    gid: 10011
    home: /home/xiangxuxin
    shell: /bin/bash
    groups: []
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: jingnanwang
    uid: 10999
    gid: 10999
    home: /home/jingnanwang
    shell: /bin/bash
    groups: []
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: chenjunhao
    uid: 11001
    gid: 11001
    home: /home/chenjunhao
    shell: /bin/bash
    groups:
      - CGCL
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: sunxuju
    uid: 11002
    gid: 11002
    home: /home/sunxuju
    shell: /bin/bash
    groups:
      - CGCL
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: zhujunwu
    uid: 11003
    gid: 11003
    home: /home/zhujunwu
    shell: /bin/bash
    groups:
      - CGCL
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: yantianyu
    uid: 12001
    gid: 12001
    home: /home/yantianyu
    shell: /bin/bash
    groups: []
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: lijiahui
    uid: 12002
    gid: 12002
    home: /home/lijiahui
    shell: /bin/bash
    groups:
      - MLLMs
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: jianan
    uid: 12003
    gid: 12003
    home: /home/jianan
    shell: /bin/bash
    groups:
      - MLLMs
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: guoxumeng
    uid: 12004
    gid: 12004
    home: /home/guoxumeng
    shell: /bin/bash
    groups:
      - MLLMs
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: yuqiao
    uid: 12005
    gid: 12005
    home: /home/yuqiao
    shell: /bin/bash
    groups: []
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: yangqingyi
    uid: 12006
    gid: 12006
    home: /home/yangqingyi
    shell: /bin/bash
    groups:
      - MLLMs
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: wangguangkai
    uid: 12007
    gid: 12007
    home: /home/wangguangkai
    shell: /bin/bash
    groups:
      - MLLMs
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: guoxufei
    uid: 12008
    gid: 12008
    home: /home/guoxufei
    shell: /bin/bash
    groups:
      - MLLMs
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: hejingjing
    uid: 12009
    gid: 12009
    home: /home/hejingjing
    shell: /bin/bash
    groups:
      - MLLMs
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: liuwenjie
    uid: 12010
    gid: 12010
    home: /home/liuwenjie
    shell: /bin/bash
    groups: []
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: zhangkaiyan
    uid: 12011
    gid: 12011
    home: /home/zhangkaiyan
    shell: /bin/bash
    groups:
      - MLLMs
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: youwenlong
    uid: 12012
    gid: 12012
    home: /home/youwenlong
    shell: /bin/bash
    groups:
      - MLLMs
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: zhangzhechuan
    uid: 12013
    gid: 12013
    home: /home/zhangzhechuan
    shell: /bin/bash
    groups:
      - MLLMs
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: huangjunyi
    uid: 12014
    gid: 12014
    home: /home/huangjunyi
    shell: /bin/bash
    groups:
      - MLLMs
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: chenxi
    uid: 12015
    gid: 12015
    home: /home/chenxi
    shell: /bin/bash
    groups:
      - MLLMs
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: yangye
    uid: 12016
    gid: 12016
    home: /home/yangye
    shell: /bin/bash
    groups:
      - MLLMs
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: luofangyuan
    uid: 12017
    gid: 12017
    home: /home/luofangyuan
    shell: /bin/bash
    groups:
      - MLLMs
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: maxinran
    uid: 12018
    gid: 12018
    home: /home/maxinran
    shell: /bin/bash
    groups:
      - MLLMs
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: yanruiyang
    uid: 12019
    gid: 12019
    home: /home/yanruiyang
    shell: /bin/bash
    groups:
      - MLLMs
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: qinxinsong
    uid: 12020
    gid: 12020
    home: /home/qinxinsong
    shell: /bin/bash
    groups:
      - MLLMs
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: wangzhaoxuan
    uid: 13001
    gid: 13001
    home: /home/wangzhaoxuan
    shell: /bin/bash
    groups:
      - CV3D
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: zengshipeng
    uid: 13003
    gid: 13003
    home: /home/zengshipeng
    shell: /bin/bash
    groups:
      - CV3D
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: wangminlong
    uid: 13004
    gid: 13004
    home: /home/wangminlong
    shell: /bin/bash
    groups:
      - CV3D
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: xujinfeng
    uid: 13005
    gid: 13005
    home: /home/xujinfeng
    shell: /bin/bash
    groups:
      - CV3D
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: zhoumengting
    uid: 13006
    gid: 13006
    home: /home/zhoumengting
    shell: /bin/bash
    groups:
      - CV3D
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: wanghao
    uid: 13007
    gid: 13007
    home: /home/wanghao
    shell: /bin/bash
    groups:
      - CV3D
    ssh_access:
      - epic-cluster-compute-a100-01
  - name: wangjiaxiang
    uid: 14001
    gid: 14001
    home: /home/wangjiaxiang
    shell: /bin/bash
    groups:
      - nue
    ssh_access:
      - epic-cluster-compute-a100-01
access_groups:
  - name: EPIC-RL
    gid: 20000
  - name: CGCL
    gid: 20001
  - name: MLLMs
    gid: 20002
  - name: CV3D
    gid: 20003
  - name: nue
    gid: 20004
