---
# Synchronize SlurmDBD Accounts and host-specific user Associations. This
# playbook uses MUNGE through sacctmgr and does not need database credentials.
- name: Synchronize Slurm accounts and partition associations
  hosts: controllers
  gather_facts: false
  any_errors_fatal: true
  vars_files:
    - ../vars/users.yml
    - ../vars/slurm_accounts.yml
    - ../vars/slurm_partitions.yml
  roles:
    - slurm_associations
