---
- name: Validate and synchronize EPIC cluster identities
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  vars_files:
    - ../vars/users.yml  # User and group definitions for EPIC cluster identities.
  roles:
    - identity  # Role for managing EPIC cluster identities.
